export const SPECIALIST_TYPE_LABELS = {
  private: "Consulta privada",
  institute: "Instituto",
  specialized_center: "Centro especializado",
  hospital: "Hospital",
  clinic: "Clínica",
  office: "Consultorio",
  foundation: "Fundación",
} as const;

export type SpecialistType = keyof typeof SPECIALIST_TYPE_LABELS;

export interface Specialist {
  name: string;
  specialty: string;
  // Empty when the location is unknown
  provinces: string[];
  city: string;
  address: string;
  phone: string;
  email: string;
  hospital: string;
  experience: string;
  insurance: string[];
  hours: string;
  type: SpecialistType;
  url?: string;
  social?: string;
  whatsapp?: string;
  linkedin?: string;
  foundationEmail?: string;
  appointments?: string;
}

const specialists: Specialist[] = [
  // CABA and Greater Buenos Aires: original list
  {
    name: "Dr. Osvaldo Rovere",
    specialty: "Psiquiatra",
    provinces: ["CABA"],
    city: "Recoleta",
    address: "Consulta privada",
    phone: "+54 9 11 5483-7442",
    email: "osvaldorovere@gmail.com",
    hospital: "Consulta privada",
    experience: "Especialista en TDAH adultos",
    insurance: ["OSDE"],
    hours: "Consultar",
    type: "private",
  },
  {
    name: "Dra. Norma Cristina Echavarria",
    specialty: "Psiquiatra",
    provinces: ["Buenos Aires"],
    city: "Hurlingham",
    address: "Sargento Salazar 1536 entre Hidalgo y Richieri",
    phone: "+54 11 4452-8765 | +54 9 11 6627-3265",
    whatsapp: "+54 9 11 4173-3220",
    email: "info@athentun.org",
    hospital: "ATHENTUN",
    experience: "Especialista en TDAH",
    insurance: ["Consultar"],
    hours: "Mar-Vie 8:00-11:00",
    type: "specialized_center",
    social: "@espaciotdah (Instagram), /Athentun (Facebook)",
    url: "https://www.nechavarria.com/",
  },
  {
    name: "Dra. Paula Harris Racedo",
    specialty: "Neuropsicóloga",
    provinces: ["Buenos Aires"],
    city: "Beccar",
    address: "Consultar ubicación",
    phone: "Consultar",
    whatsapp: "+54 9 11 4437-2878",
    email: "paulaharrisracedo@gmail.com",
    hospital: "Consulta privada virtual",
    experience: "Especialista en TDAH",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    social: "@phd_internacional (Instagram)",
    url: "https://sites.google.com/view/paulaharrisracedo/",
    linkedin: "https://www.linkedin.com/in/paula-harris-23a35a28/",
  },
  {
    name: "Lic. Marina Drake",
    specialty: "Neuropsicóloga",
    provinces: ["CABA"],
    city: "CABA",
    address: "Esmeralda 961 6° Piso, Depto. H",
    phone: "+54 11 4311-7864",
    email: "contacto@neuropsicologia.com.ar",
    hospital: "NEUROPSIC Consultorios",
    experience: "Neuropsicología",
    insurance: ["Consultar"],
    hours: "Lun-Vie 14:00-19:00",
    type: "office",
    url: "https://www.neuropsicologia.com.ar/",
    whatsapp: "+54 9 11 6665-9139",
  },
  {
    name: "Dra. Natalia Fiorentino",
    specialty: "Neuropsicóloga",
    provinces: ["CABA"],
    city: "CABA",
    address: "M.T de Alvear 1632",
    phone: "0810-266-4203",
    email: "info@ineco.org.ar",
    hospital: "INECO - Instituto de Neurología Cognitiva",
    experience: "Programa de diagnóstico de TDAH",
    insurance: ["Consultar"],
    hours: "Lun-Vie",
    type: "institute",
    url: "https://www.ineco.org.ar/programa-de-diagnostico-tdah/",
  },
  {
    name: "INECO",
    specialty: "Centro Especializado",
    provinces: ["CABA"],
    city: "CABA",
    address: "M.T de Alvear 1632",
    phone: "0810-266-4203",
    email: "info@ineco.org.ar",
    hospital: "INECO",
    experience: "Instituto de neurología cognitiva con programa de diagnóstico de TDAH",
    insurance: ["Múltiples obras sociales"],
    hours: "Lun-Vie 8:00-18:00",
    type: "specialized_center",
    url: "https://www.ineco.org.ar/programa-de-diagnostico-tdah/",
  },
  {
    name: "Dra. Rosario Figueras",
    specialty: "Psiquiatra",
    provinces: ["CABA"],
    city: "CABA",
    address: "M.T de Alvear 1632",
    phone: "+54 9 291 573-2919",
    email: "info@ineco.org.ar",
    hospital: "INECO - Instituto de Neurología Cognitiva",
    experience: "Especialista en TDAH",
    insurance: ["Consultar"],
    hours: "Lun-Vie",
    type: "institute",
  },
  {
    name: "Dra. Mirta Romalde",
    specialty: "Psiquiatra",
    provinces: ["CABA"],
    city: "CABA",
    address: "M.T de Alvear 1632",
    phone: "+54 9 11 5929-9467",
    email: "info@ineco.org.ar",
    hospital: "INECO - Instituto de Neurología Cognitiva",
    experience: "Especialista en TDAH",
    insurance: ["Consultar"],
    hours: "Lun-Vie",
    type: "institute",
  },
  {
    name: "Dr. Gabriel Emilio Brenner",
    specialty: "Psiquiatra",
    provinces: ["CABA"],
    city: "CABA",
    address: "Consultar ubicación",
    phone: "+54 9 11 2794-0095",
    email: "info@inecap.org",
    hospital: "INECAP - Instituto de Neurociencia Cognitiva Aplicada",
    experience: "Especialista en TDAH",
    insurance: ["Consultar"],
    hours: "Lun-Vie 9:00-20:00",
    type: "institute",
    social: "@inecap.tdah (Instagram), /inecap.org (Facebook)",
    url: "https://inecap.org/",
  },
  {
    name: "FLENI",
    specialty: "Centro Especializado",
    provinces: ["CABA"],
    city: "Belgrano",
    address: "Montañeses 2325, Belgrano, CABA",
    phone: "+54 11 5777-3200",
    email: "info@fleni.org.ar",
    hospital: "FLENI",
    experience: "Fundación especializada en neurología con departamento de neurología cognitiva y neuropsiquiatría",
    insurance: ["Múltiples obras sociales"],
    hours: "Lun-Vie 8:00-20:00",
    type: "specialized_center",
    url: "https://www.fleni.org.ar/",
  },
  {
    name: "ATHENTUN",
    specialty: "Centro Especializado",
    provinces: ["Buenos Aires"],
    city: "Hurlingham",
    address: "Sargento Salazar 1536 entre Hidalgo y Richieri",
    phone: "+54 11 4452-8765 | +54 9 11 6627-3265",
    email: "info@athentun.org",
    hospital: "ATHENTUN",
    experience: "Centro especializado en TDAH con atención interdisciplinaria",
    insurance: ["Consultar"],
    hours: "Mar-Vie 8:00-11:00",
    type: "specialized_center",
    social: "@espaciotdah (Instagram), /Athentun (Facebook)",
    url: "https://www.nechavarria.com/",
  },
  {
    name: "INECAP",
    specialty: "Centro Especializado",
    provinces: ["CABA"],
    city: "CABA",
    address: "Servicios 100% online",
    phone: "Consultar",
    email: "info@inecap.org",
    hospital: "INECAP",
    experience: "Diagnóstico y tratamiento de TDAH en jóvenes y adultos",
    insurance: ["Consultar"],
    hours: "Servicios online disponibles",
    type: "specialized_center",
    social: "@inecap.tdah (Instagram), /inecap.org (Facebook)",
    url: "https://inecap.org/",
  },
  {
    name: "Dra. Ariadna Echavarria",
    specialty: "Psiquiatra",
    provinces: ["Buenos Aires"],
    city: "Hurlingham",
    address: "Sargento Salazar 1536 entre Hidalgo y Richieri",
    phone: "Consultar",
    whatsapp: "+54 9 11 2391-3130",
    email: "ariadnaechavarria@gmail.com",
    hospital: "ATHENTUN",
    experience: "Especialista en TDAH",
    insurance: ["Consultar"],
    hours: "Mar-Vie 8:00-11:00",
    type: "specialized_center",
  },
  {
    name: "Dra. Valeria Berlin",
    specialty: "Psiquiatra",
    provinces: [],
    city: "Consultar",
    address: "Consultar",
    phone: "Consultar",
    whatsapp: "+54 9 11 2643-2761",
    email: "Consultar",
    hospital: "Campus Neurodiverso",
    experience: "Psiquiatra",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    social: "@psiquiatra.valeriaberlin (Instagram)",
    url: "https://campusneurodiverso.com/",
  },
  {
    name: "Dr. Chrem Mendez Patricio",
    specialty: "Neurólogo",
    provinces: ["CABA"],
    city: "CABA",
    address: "FLENI",
    phone: "+54 11 5777-3200",
    email: "Consultar",
    hospital: "FLENI - Neurología Cognitiva",
    experience: "Neurología Cognitiva - TDAH",
    insurance: ["Múltiples obras sociales"],
    hours: "Lun-Vie 8:00-20:00",
    type: "hospital",
  },
  {
    name: "Dr. Juan Pablo García Lombardi",
    specialty: "Neurólogo",
    provinces: ["CABA"],
    city: "Belgrano",
    address: "FLENI - Montañeses 2325, 8vo piso, Belgrano, CABA",
    phone: "+54 11 5777-3200",
    email: "jpabloglombardi@gmail.com",
    hospital: "FLENI",
    experience: "Neurología cognitiva/Neuropsiquiatria. Psiquiatra - Magíster en Neuropsicofarmacología. También atiende en La Plata - Instituto de Neurociencias Alexander Luria (02214511811)",
    insurance: ["Múltiples obras sociales"],
    hours: "Lun-Vie 8:00-20:00",
    type: "hospital",
  },
  {
    name: "Dra. María Cecilia Rodríguez",
    specialty: "Psiquiatra",
    provinces: ["CABA"],
    city: "CABA",
    address: "Hospital Italiano",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Hospital Italiano",
    experience: "Psiquiatría - Buen trato con pacientes",
    insurance: ["Múltiples obras sociales"],
    hours: "Consultar",
    type: "hospital",
    url: "https://www1.hospitalitaliano.org.ar/#!/home/psiquiatria/inicio",
  },
  {
    name: "Dra. Cecilia Di Virgilio",
    specialty: "Pediatra",
    provinces: ["Buenos Aires"],
    city: "La Plata",
    address: "20 Nº 389 e/39 y 40",
    phone: "+54 221 523-6577",
    email: "neurocienciascienn@gmail.com",
    hospital: "CIENN - Solo niños",
    experience: "Centro especializado en neurodesarrollo infantil",
    insurance: ["Consultar"],
    hours: "Lun-Vie 8:00-20:00, Sáb 9:00-13:00",
    type: "specialized_center",
    whatsapp: "+54 9 221 552-6999",
    appointments: "423-3792",
    social: "@c.i.e.n.n (Instagram), /neurocienciasCIENN (Facebook)",
  },
  {
    name: "Dra. Silvina Gutierrez",
    specialty: "Psiquiatra",
    provinces: ["Buenos Aires"],
    city: "La Plata",
    address: "115 Nro. 425 (Clínica San Juan)",
    phone: "+54 221 641-9144",
    email: "Consultar",
    hospital: "Clínica San Juan",
    experience: "Especialista en TDAH",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "clinic",
  },
  {
    name: "Lic. Luis Santiago Vaggione",
    specialty: "Psicólogo",
    provinces: ["Córdoba"],
    city: "Córdoba Capital",
    address: "Fundación Nascendi",
    phone: "Consultar",
    email: "lsvaggione@yahoo.com.ar",
    hospital: "Fundación Nascendi",
    foundationEmail: "fundacionnascendi@gmail.com",
    experience: "Especialista en TDAH",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "foundation",
    social:
      "@luissantiagovaggione (Instagram), /luissantiago.vaggione (Facebook)",
  },

  // Educational psychologists
  {
    name: "Crianza Positiva",
    specialty: "Psicopedagogía",
    provinces: ["CABA"],
    city: "Caballito",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Centro Categorizado y Equipo Interdisciplinario",
    experience: "Problematicas de Conducta y Dificultades Emocionales",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    url: "https://www.google.com/search?q=Crianza+Positiva+Buenos+Aires&stick=H4sIAAAAAAAAAONgecT4npFb4OWPe8JSTxknrTl5jfEeIxdXcEZ-uWteSWZJpVAAFxuUpcIlKMWrn65vaJhlYGRakZxrqcEgxc-FKiSloMTFe3x59GtR41Uad7WEOEUfWBRxn94zVVByJd-LuqXiM4Q0uTiDUnMSS1JTQvKFZLh4pTj1c_UNDHMqTXOBBnJzIbhKwUbuuy5NO8fmKMgABEdSwx2kNJWEuThCEivy8_JzKwUP_P-_____9_ZKQlzsnsU--cmJOYKv9jEm6HwEinFyAjUd2Lz8vb0WQ9O-FYfYWDgYBRh4FrHKOhdlJuZVJSoE5BdnlmSWJSo4labm5RcrOGYWpRYDAJy1e1EVAQAA&sa=X&ved=2ahUKEwjp74CJq7HqAhUSGKwKHePXBvYQ6RMwC3oECAwQBA&biw=1440&bih=789"
  },
  {
    name: "Lic. Liliana Fonseca",
    specialty: "Psicopedagogía",
    provinces: ["Buenos Aires"],
    city: "San Isidro",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psicopedagoga",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    url: "http://aprendizajeyfamilia.com/"
  },
  {
    name: "Lic. Margarita Peña",
    specialty: "Psicopedagogía",
    provinces: ["Buenos Aires"],
    city: "Bella Vista",
    address: "San Martín 2325, Bella Vista, Bs. As.",
    phone: "Consultar",
    whatsapp: "+54 9 11 3005-4000",
    email: "maggiepenia@gmail.com",
    hospital: "Consulta privada",
    experience: "Psicopedagogía",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Centro de integración escolar",
    specialty: "Centro Especializado",
    provinces: ["CABA"],
    city: "CABA",
    address: "Consultar ubicación específica",
    phone: "+54 11 4326-1971",
    whatsapp: "+54 9 11 5063-7542",
    email: "contacto@cieintegracion.com",
    hospital: "Centro de integración escolar",
    experience: "Acompañamiento escolar",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    url: "http://www.integracionescolar.com.ar/contacto/"
  },
  {
    name: "Lic. Graciela Bernardi",
    specialty: "Psicopedagogía",
    provinces: ["Buenos Aires"],
    city: "Zona Oeste",
    address: "Consultar ubicación específica",
    phone: "+54 9 11 5932-7259",
    email: "gracielabernardi@yahoo.com",
    hospital: "Consulta privada",
    experience: "Psicopedagoga, especialista en neurodesarrollo",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Escuela de Equitación Hipocampo",
    specialty: "Centro Especializado",
    provinces: ["CABA"],
    city: "Palermo",
    address: "Av. Figueroa Alcorta 5100, Palermo, CABA",
    phone: "+54 9 11 5015-2666",
    email: "Consultar",
    hospital: "Escuela de Equitación Hipocampo",
    experience: "Equinoterapia complementaria",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    url: "http://www.escuelahipocampo.org/equinoterapia.html"
  },
  {
    name: "Lic. Antonela Rubio",
    specialty: "Psicopedagogía",
    provinces: ["Buenos Aires"],
    city: "La Plata",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "antonela.rubio@hotmail.com",
    hospital: "Consulta privada",
    experience: "Formada en TDAH y aprendizaje en niños y adolescentes",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Analía Dussin",
    specialty: "Psicopedagogía",
    provinces: ["Córdoba"],
    city: "San Francisco",
    address: "Paraguay 1565, San Francisco, Córdoba",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Lic. en Psicopedagogía",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    social: "@analiadussin.psp (Instagram)",
    url: "https://instagram.com/analiadussin.psp?igshid=19bgkdtzndn9e"
  },
  {
    name: "Lic. Romina del Río",
    specialty: "Psicopedagogía",
    provinces: ["Buenos Aires"],
    city: "San Isidro",
    address: "Brasil 724, San Isidro",
    phone: "Consultar",
    whatsapp: "+54 9 11 6140-9612",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psicopedagoga",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. María Guillermina Mujica",
    specialty: "Psicopedagogía",
    provinces: ["Buenos Aires"],
    city: "Bernal",
    address: "Calle Ituzaingo 456 Bernal",
    phone: "+54 11 4251-6988",
    email: "Guillerminamujica@yahoo.com.ar",
    hospital: "Consulta privada",
    experience: "Psicopedagoga - También atiende online",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Ines Christie Newbery",
    specialty: "Psicopedagogía",
    provinces: ["CABA", "Buenos Aires"],
    city: "Recoleta/Bella Vista",
    address: "Callao 1673, Recoleta, CABA | Scott 2488, Bella Vista, Buenos Aires",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psicopedagoga Clínica - Atiende en dos consultorios",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "ÁBACO Interdisciplina",
    specialty: "Centro Especializado",
    provinces: ["Córdoba"],
    city: "Río Tercero",
    address: "Esperanza 1270 1278, X5850 Río Tercero, Córdoba",
    phone: "+54 3571 41-1469",
    email: "Consultar",
    hospital: "Centro interdisciplinario",
    experience: "Centro interdisciplinario",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center"
  },
  {
    name: "Lic. Antonella Rizzo",
    specialty: "Psicopedagogía",
    provinces: ["CABA"],
    city: "Caballito",
    address: "Av. Rivadavia y Acoyte (a 1 cuadra) zona Caballito",
    phone: "+54 9 11 4916-3164",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Licencia en psicopedagogía neurocognitiva",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Florencia Foglia",
    specialty: "Psicopedagogía",
    provinces: ["Santa Fe"],
    city: "Santa Fe",
    address: "Gdor. Crespo 2938, S3000 Santa Fe de la Vera Cruz",
    phone: "+54 9 358 429-8457",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psicopedagoga",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },

  // More psychiatrists and neurologists
  {
    name: "Dra. Lorena María Santillán",
    specialty: "Neurólogo",
    provinces: ["CABA"],
    city: "CABA",
    address: "Hospital Italiano - Servicio de Neurología Pediátrica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Hospital Italiano",
    experience: "Pediatra y neuróloga",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "institute",
    url: "https://www.niba.com.ar/"
  },
  {
    name: "Hospital Italiano - Equipo de Neurología",
    specialty: "Centro Especializado",
    provinces: ["CABA"],
    city: "CABA",
    address: "Hospital Italiano",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Hospital Italiano",
    experience: "Equipo de neurología",
    insurance: ["Hospital Italiano"],
    hours: "Consultar",
    type: "hospital",
    url: "https://www.hospitalitaliano.org.ar/#!/home/neurologia/seccion/14251"
  },
  {
    name: "Dra. Paola Grabow",
    specialty: "Psiquiatra",
    provinces: ["CABA"],
    city: "Belgrano",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psiquiatría infantil",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    linkedin: "https://ar.linkedin.com/in/paola-grabow-1b8b5941?src=aff-lilpar&veh=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&trk=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&clickid=2pe2qITY8xyOT42wUx0Mo3chUkiUlV3TUQUFVM0&irgwc=1"
  },
  {
    name: "Dr. Claudio Michanie",
    specialty: "Psiquiatra",
    provinces: ["CABA"],
    city: "CABA",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psiquiatría Infantil y Adolescente",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    url: "https://psiquiatria.com/directorio/claudio-michanie"
  },
  {
    name: "Dr. Guillermo Bernaldo de Quiros",
    specialty: "Neurólogo",
    provinces: ["CABA"],
    city: "CABA",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Neurologo infantil",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    url: "https://www.google.com/search?ei=RkH_Xs-VEcu1tAaw86XYCA&q=Dr+Guillermo+Bernaldo+de+Quiros+bs+as+&oq=Dr+Guillermo+Bernaldo+de+Quiros+bs+as+&gs_lcp=CgZwc3ktYWIQAzIFCCEQoAE6AggAUO5YWK2KAWD1iwFoBXAAeACAAboBiAHUDJIBBDAuMTOYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwjP0IqOprHqAhXLGs0KHbB5CYsQ4dUDCAw&uact=5"
  },
  {
    name: "Dr. Pablo Jorrat",
    specialty: "Neurólogo",
    provinces: ["CABA"],
    city: "CABA",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Neurólogo infantil",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    url: "https://www.google.com/search?q=dr+Pablo+Jorrat+bs+as&oq=dr+Pablo+Jorrat+bs+as&aqs=chrome..69i57j0l7.2214j0j9&sourceid=chrome&ie=UTF-8"
  },
  {
    name: "Dr. Juan Tripoli",
    specialty: "Neurólogo",
    provinces: ["CABA"],
    city: "Belgrano",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Neurología Pediátrica",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    url: "http://pediatriabelgranor.com/nosotros/dr-juan-tripoli/"
  },
  {
    name: "Dra. Norma Taddey",
    specialty: "Psiquiatra",
    provinces: ["Buenos Aires"],
    city: "Vicente López",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psiquiatra infanto juvenil",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    linkedin: "https://ar.linkedin.com/in/norma-taddey-10975422?src=aff-lilpar&veh=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&trk=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&clickid=2pe2qITY8xyOT42wUx0Mo3chUkiUlDU6UQUFVM0&irgwc=1"
  },
  {
    name: "Dra. Sara Panossian",
    specialty: "Neurólogo",
    provinces: ["Buenos Aires"],
    city: "Bella Vista",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Neuróloga infanto juvenil",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    url: "https://www.doxadoctor.com/medicos/Panossian-Sara-Irene"
  },
  {
    name: "Dr. Diego Miniño",
    specialty: "Psiquiatra",
    provinces: ["Buenos Aires"],
    city: "Lanús",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    whatsapp: "+54 9 11 4424-8825",
    email: "diegoadrianminino@gmail.com",
    hospital: "Consulta privada",
    experience: "Psiquiatra",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    url: "https://www.saludmentallanus.com/staff"
  },
  {
    name: "CIENN",
    specialty: "Centro Especializado",
    provinces: ["Buenos Aires"],
    city: "La Plata",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Centro Modelo de Neurociencias Infantojuvenil",
    experience: "Diagnosticos y Tratamientos Interdisciplinarios. Neurodesarrollo y Nutrición",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    url: "http://cienn.com.ar/"
  },
  {
    name: "Dr. Mariano Pala",
    specialty: "Pediatra",
    provinces: ["Buenos Aires"],
    city: "Mar del Plata",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Pediatra y psiquiatra infanto juvenil",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    linkedin: "https://ar.linkedin.com/in/mariano-pala-6294768a"
  },
  {
    name: "Dr. Marcon Laureano",
    specialty: "Neurólogo",
    provinces: ["Buenos Aires"],
    city: "Mar del Plata",
    address: "INEDEM",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Instituto de Neurología y Desarrollo Marcón",
    experience: "Instituto de Neurología y Desarrollo",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "institute",
    url: "http://inedem.com.ar/"
  },
  {
    name: "Dr. Nicolás Schnitzler",
    specialty: "Neurólogo",
    provinces: ["CABA"],
    city: "CABA",
    address: "Fundación Favaloro",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Fundación Favaloro",
    experience: "Jefe de Neurología Infantil",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "hospital",
    url: "https://www.fundacionfavaloro.org/neurologia-infantil/"
  },
  {
    name: "Dra. María Susana Mosquera",
    specialty: "Psiquiatra",
    provinces: ["Buenos Aires"],
    city: "San Isidro",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psiquiatra",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    url: "https://www.doctoraliar.com/maria-susana-mosquera/psiquiatra/san-isidro"
  },
  {
    name: "Dra. Varinia A. Frau Alveal",
    specialty: "Psiquiatra y Legista",
    provinces: ["CABA"],
    city: "CABA",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Médico Psiquiatra y Legista. Docente",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    url: "https://www.google.com/search?ei=Eln_XqLbI4KQtQWj6ZyACA&q=Varinia+Frau+Alveal+psiquiatria+&oq=Varinia+Frau+Alveal+psiquiatria+&gs_lcp=CgZwc3ktYWIQAzIFCCEQoAEyBQghEKABOgIIADoGCAAQFhAeUITNAVja3gFg3t8BaABwAHgAgAGwBYgBkhKSAQczLTIuMi4xmAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwiirI_nvLHqAhUCSK0KHaM0B4AQ4dUDCAw&uact=5"
  },
  {
    name: "Dr. Adi Javier Nadin",
    specialty: "Neurólogo",
    provinces: ["Mendoza"],
    city: "Godoy Cruz",
    address: "Panamericana 2650, Godoy Cruz, Mendoza",
    phone: "+54 261 439-8010",
    email: "Consultar",
    hospital: "Centro Médico Palmares",
    experience: "Neurología en niños y adolescentes",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    url: "http://www.centromedicopalmares.com/medicos/dr-adi-javier-nadin/"
  },
  {
    name: "Dra. Carolina Remedi",
    specialty: "Psiquiatra",
    provinces: ["Córdoba"],
    city: "Córdoba Capital",
    address: "Av. Velez Sarsfield 1460",
    phone: "Consultar",
    email: "carore.remedi101@gmail.com",
    hospital: "CETES",
    experience: "Psiquiatra",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    url: "http://cetes.com.ar/ya-nos-trasladamos/"
  },
  {
    name: "Dr. José Dominguez",
    specialty: "Psiquiatra",
    provinces: ["Santa Fe"],
    city: "Santa Fe",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psiquiatra",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    url: "https://www.google.com/search?q=Jos%C3%A9+Dom%C3%ADnguez+psiquiatra+santa+fe&oq=Jos%C3%A9+Dom%C3%ADnguez+psiquiatra+santa+fe&aqs=chrome..69i57.2901j0j4&sourceid=chrome&ie=UTF-8"
  },
  {
    name: "Dra. Mariela Labath",
    specialty: "Neurólogo",
    provinces: ["Santa Fe"],
    city: "Paraná",
    address: "Consultorios Interdisciplinarios Puerto Nuevo",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consultorios Interdisciplinarios Puerto Nuevo",
    experience: "Neurología",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "office",
    social: "/Consultorios-Interdisciplinarios-Puerto-Nuevo-902522106535440 (Facebook)",
    url: "https://es-la.facebook.com/pg/Consultorios-Interdisciplinarios-Puerto-Nuevo-902522106535440/about/"
  },
  {
    name: "Dr. Eduardo Monese",
    specialty: "Pediatra",
    provinces: ["Santa Fe"],
    city: "Santa Fe Capital",
    address: "Mendoza 3373, Santa Fe Capital",
    phone: "+54 342 453-0374",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Neurólogo y pediatra",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    url: "https://www.doctoraliar.com/eduardo-j-monese/pediatra/santa-fe-capital"
  },
  {
    name: "Dra. Viviana Rios",
    specialty: "Neurólogo",
    provinces: ["Santa Fe"],
    city: "Santa Fe",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Neuróloga",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    url: "https://www.google.com/search?q=Dra+Viviana+Rios+santa+fe&oq=Dra+Viviana+Rios+santa+fe+&aqs=chrome..69i57.1746j0j4&sourceid=chrome&ie=UTF-8"
  },
  {
    name: "Dra. Stephanie Schon",
    specialty: "Psiquiatra",
    provinces: ["Buenos Aires"],
    city: "Mar del Plata",
    address: "Consultar ubicación específica",
    phone: "+54 223 451-9651",
    email: "stephyschon@hotmail.com",
    hospital: "Consulta privada",
    experience: "Psiquiatra",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Dr. Ricardo Rojas",
    specialty: "Psiquiatra",
    provinces: ["CABA"],
    city: "CABA",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    whatsapp: "+54 9 223 579 6683",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psiquiatra adultos, adicciones y TDAH",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Dra. Natalia Barrios",
    specialty: "Psiquiatra",
    provinces: ["Buenos Aires"],
    city: "La Matanza",
    address: "Consultar ubicación específica",
    phone: "+54 9 11 4157-9425",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psiquiatra",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "CPG Salud",
    specialty: "Centro Especializado",
    provinces: ["Buenos Aires"],
    city: "Zona Norte",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    whatsapp: "+54 9 11 3039-0164",
    email: "Consultar",
    hospital: "CPG Salud",
    experience: "Institución privada especializada en Salud Mental - asistencia, diagnóstico y tratamiento desde 2005",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    url: "http://www.cpgsalud.com.ar/contacto.html"
  },
  {
    name: "Dra. Stella Maris Ramirez",
    specialty: "Psiquiatra",
    provinces: ["CABA"],
    city: "CABA",
    address: "Hospital Churruca Visca",
    phone: "+54 11 4909-4100 (interno 4847)",
    email: "Consultar",
    hospital: "Hospital Churruca Visca - Servicio de Salud Mental Infanto Juvenil",
    experience: "Psiquiatra del Servicio de Salud Mental Infanto Juvenil",
    insurance: ["Hospital público"],
    hours: "Consultar",
    type: "hospital"
  },
  {
    name: "Integral-mente",
    specialty: "Centro Especializado",
    provinces: ["Buenos Aires"],
    city: "Villa Luzuriaga",
    address: "Miró 2534, Villa Luzuriaga, Bs. As.",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Integral-mente",
    experience: "Equipo Interdisciplinario de Desarrollo",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    whatsapp: "+54 9 11 6605-4391",
    url: "http://www.integral-mente.com.ar/"
  },
  {
    name: "Dr. Eduardo Galli",
    specialty: "Neurólogo",
    provinces: ["Santa Fe"],
    city: "Rafaela",
    address: "Calle 25 de Mayo 2048 - AMUR",
    phone: "+54 342 452-5891",
    whatsapp: "+54 342 453-5606",
    email: "Consultar",
    hospital: "AMUR",
    experience: "Neurólogo y Neuropsicologo - Solo evaluación. No tiene equipo de profesionales (Psiquiatra y Psicólogo) para el tratamiento",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center"
  },
  {
    name: "Dra. Silvina Rita Riera",
    specialty: "Psiquiatra",
    provinces: ["Mendoza"],
    city: "Mendoza",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    whatsapp: "+54 9 261 472-4886",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psiquiatra Infantojuvenil",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Dr. Guido Norberto Luppi",
    specialty: "Pediatra",
    provinces: ["CABA"],
    city: "CABA",
    address: "Uruguay 1134 2do piso, Capital Federal",
    phone: "+54 11 5217-1382",
    email: "drguidoluppi@gmail.com",
    hospital: "Consulta privada",
    experience: "Medico pediatra y psiquiatra innfantojuvenil. Realiza diagnóstico y tratamiento de TDAH y hace consultas virtuales y presenciales",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    whatsapp: "+54 11 4412-0880",
    url: "https://forms.gle/xym8jNQ6xMsSBT5T8"
  },

  // Pediatricians
  {
    name: "Dra. Ángeles Menendez",
    specialty: "Pediatra del Neurodesarrollo",
    provinces: ["CABA"],
    city: "CABA",
    address: "Centro Pediátrico del Desarrollo Creciendo Juntos",
    phone: "+54 9 11 5704-4655",
    email: "Consultar",
    hospital: "Centro Pediátrico del Desarrollo Creciendo Juntos",
    experience: "Pediatra del neurodesarrollo",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    social: "/CentroPediatricoCreciendoJuntos (Facebook)",
    url: "https://es-la.facebook.com/pg/CentroPediatricoCreciendoJuntos/about/?ref=page_internal"
  },
  {
    name: "Dra. Debora Abolsky",
    specialty: "Pediatra",
    provinces: ["Buenos Aires"],
    city: "Luján",
    address: "Consultar ubicación específica",
    phone: "+54 232 047-0009",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Pediatra",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Dr. Juan José López Luro",
    specialty: "Pediatra del Desarrollo",
    provinces: ["Río Negro"],
    city: "Neuquén",
    address: "Consultar ubicación específica",
    phone: "+54 299 467-5599",
    email: "consultoriolopezlurovitale@gmail.com",
    hospital: "Consulta privada",
    experience: "Pediatra del Desarrollo",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },

  // Psychologists and CBT
  {
    name: "Lic. Facundo Torres",
    specialty: "Psicólogo",
    provinces: ["Buenos Aires"],
    city: "Tigre",
    address: "CEPSIN",
    phone: "Consultar",
    email: "Consultar",
    hospital: "CEPSIN",
    experience: "Psicólogo infantojuvenil",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    url: "https://www.cepsin.com.ar/psicologos.html"
  },
  {
    name: "Lic. Cecilia Cid",
    specialty: "Psicólogo",
    provinces: ["Buenos Aires"],
    city: "Zona Oeste",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    whatsapp: "+54 9 11 6116-9753",
    email: "ceciliascid@gmail.com",
    hospital: "Consulta privada",
    experience: "Psicóloga niños y adolescentes TCC",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Lorena Lancha",
    specialty: "Psicólogo",
    provinces: ["Buenos Aires"],
    city: "Zona Oeste",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    whatsapp: "+54 9 11 6605-4391",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psicóloga especializada en neurodesarrollo. TCC",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Bettina Arredondo",
    specialty: "Psicólogo",
    provinces: ["Buenos Aires"],
    city: "Temperley",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    whatsapp: "+54 9 11 5772-5296",
    email: "psiarredondobettina@gmail.com",
    hospital: "Consulta privada",
    experience: "Psicologa cognitiva",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Laura Alcocer",
    specialty: "Psicólogo",
    provinces: ["Buenos Aires"],
    city: "La Plata",
    address: "CETECO",
    phone: "Consultar",
    email: "Consultar",
    hospital: "CETECO",
    experience: "Psicóloga, directora de CETECO",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    url: "http://www.cetecolaplata.com.ar/"
  },
  {
    name: "Lic. Sharon Suzanne",
    specialty: "Psicólogo",
    provinces: ["CABA"],
    city: "CABA",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    whatsapp: "+54 9 11 2253-1362",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psicologa infanto-juvenil - autismo, TDAH, TEA, dislexia. Enfoque psicoeducativo",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    linkedin: "https://ar.linkedin.com/in/sharon-suzanne-mujica-33546338?src=aff-lilpar&veh=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&trk=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&clickid=2pe2qITY8xyOT42wUx0Mo3chUkiUlIQKUQUFVM0&irgwc=1"
  },
  {
    name: "Lic. Alberto Luis Fernandez",
    specialty: "Psicólogo",
    provinces: ["Córdoba"],
    city: "Córdoba Capital",
    address: "Centro Cortex: Calle Chile 279",
    phone: "+54 351 662-5405",
    email: "Consultar",
    hospital: "Centro Cortex",
    experience: "Psicólogo",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    url: "https://www.cortexneuroterapias.com.ar/quienes-somos"
  },
  {
    name: "Lic. Luciana Tapia",
    specialty: "Psicólogo",
    provinces: ["Buenos Aires"],
    city: "Necochea",
    address: "Consultar ubicación específica",
    phone: "+54 226 248-0577",
    email: "tapialuciana@hotmail.com",
    hospital: "Consulta privada",
    experience: "Psicóloga cognitivo conductual",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Iris Wolff",
    specialty: "Psicólogo",
    provinces: ["CABA"],
    city: "CABA",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    email: "irisworff01@gmail.com",
    hospital: "Consulta privada",
    experience: "Psicóloga cognitiva",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Elisa Chisleanschi",
    specialty: "Psicólogo",
    provinces: ["Buenos Aires"],
    city: "Bella Vista",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    whatsapp: "+54 11 4666-4395",
    email: "tinachisle@hotmail.com",
    hospital: "Consulta privada",
    experience: "Psicóloga",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Eleonora Giusti",
    specialty: "Psicólogo",
    provinces: ["CABA"],
    city: "CABA",
    address: "Consultar ubicación específica",
    phone: "+54 9 11 6229-7355",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psicologa adultos cognitiva",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "TCM Terapia Cognitiva",
    specialty: "Centro Especializado",
    provinces: ["Buenos Aires"],
    city: "La Matanza",
    address: "Zaqueira 6880, Bs. As.",
    phone: "+54 9 11 3066-6880",
    email: "Consultar",
    hospital: "TCM Terapia Cognitiva",
    experience: "Terapia cognitiva",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    social: "@tcm.psic (Instagram)",
    url: "https://tcmcognitiva.com/"
  },
  {
    name: "Lic. Carolina Piñero",
    specialty: "Psicólogo",
    provinces: ["Buenos Aires"],
    city: "Tandil",
    address: "Consultar ubicación específica",
    phone: "+54 9 11 4039-2057",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Piscóloga",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Alejandra Perez",
    specialty: "Neuropsicóloga",
    provinces: ["Buenos Aires"],
    city: "San Isidro",
    address: "Alem 265, San Isidro",
    phone: "+54 9 11 6593-1494",
    email: "alejandraperezturnos@gmail.com",
    hospital: "Consulta privada",
    experience: "Psicóloga especializada en neuropsicología",
    insurance: ["Particular"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Silvana Soave",
    specialty: "Psicólogo",
    provinces: ["Buenos Aires"],
    city: "Necochea",
    address: "Calle 60-2780",
    phone: "+54 226 253-0111",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psicóloga cognitivo conductual",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Manuel Pastene",
    specialty: "Psicólogo",
    provinces: ["Buenos Aires"],
    city: "Vicente Lopez",
    address: "Santa Rosa 1393, Vicente Lopez",
    phone: "Consultar",
    whatsapp: "+54 11 4089-7200",
    email: "manuelpastene@gmail.com",
    hospital: "Consulta privada",
    experience: "Lic. en Psicología y especializado en el diagnóstico y tratamiento para jóvenes y adultos con TDAH",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Romina Rosbelke",
    specialty: "Psicólogo",
    provinces: ["Buenos Aires"],
    city: "Quilmes",
    address: "Calle brandzen 253, Quilmes",
    phone: "+54 9 11 6714-2890",
    email: "Romina_rosbelke@hotmail.com",
    hospital: "Consulta privada",
    experience: "Psicóloga infantil - Atiende también online",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Maria Gabriela Marina",
    specialty: "Psicólogo",
    provinces: ["CABA"],
    city: "CABA",
    address: "Atiende online",
    phone: "+54 9 11 3230-6783",
    email: "mariamarinapsi@gmail.com",
    hospital: "Consulta privada online",
    experience: "Licenciada en psicología/Terapeuta cognitivo conductual /Terapeuta EMDR",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Patricia Simao",
    specialty: "Psicólogo",
    provinces: ["CABA"],
    city: "CABA",
    address: "Consultar ubicación específica",
    phone: "Consultar",
    whatsapp: "+54 9 11 6494 5376",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psicologa infantil especializada en altas capacidades y TDAH",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Lila Perinot",
    specialty: "Neuropsicóloga",
    provinces: ["CABA"],
    city: "Palermo",
    address: "Ciudad de la Paz 561, Palermo",
    phone: "+54 9 11 3147-8100",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Neuropsicologa - Adultos",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Celeste Campano",
    specialty: "Psicólogo",
    provinces: ["CABA"],
    city: "Caballito",
    address: "Calle Lautaro 46 (Esquina Avenida Rivadavia) Caballito",
    phone: "Consultar",
    email: "Consultar",
    hospital: "Crianza positiva",
    experience: "Crianza positiva y trabaja en talleres de habilidades sociales con grupos de niños con TDAH",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    social: "@crianzapositivaargentina (Instagram)",
    url: "https://instagram.com/crianzapositivaargentina?igshid=YmMyMTA2M2Y="
  },
  {
    name: "Lic. Anahi Lujan Garayo",
    specialty: "Psicólogo",
    provinces: ["La Pampa"],
    city: "Santa Rosa",
    address: "Av. Belgrano Norte, Santa Rosa 6300 La Pampa",
    phone: "Consultar",
    whatsapp: "+54 9 2954 33-6970",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psicologa",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Castro Zamparella Tatiana",
    specialty: "Psicólogo",
    provinces: ["Córdoba"],
    city: "Córdoba Capital",
    address: "CNR",
    phone: "Consultar",
    email: "cnrcerebroysalud@gmail.com",
    hospital: "CNR",
    experience: "Psicóloga",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center"
  },
  {
    name: "Lic. Maria Laura De Feo",
    specialty: "Psicólogo",
    provinces: ["Santa Fe"],
    city: "Santa Fe",
    address: "San Jerónimo 2020, Santa Fe de la Vera Cruz",
    phone: "+54 9 342 503-2995",
    email: "Consultar",
    hospital: "Consulta privada",
    experience: "Psicóloga (TCC)",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Lic. Vivian Alexia Hudson Figueroa",
    specialty: "Psicólogo",
    provinces: ["CABA"],
    city: "Belgrano",
    address: "Belgrano (a una cuadra de Lacroze y cabildo)",
    phone: "+54 9 11 5528-4448",
    email: "vivianalexia@hotmail.com",
    hospital: "Consulta privada",
    experience: "Psicóloga de adultos y parejas - Atiende online o presencial",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private",
    social: "@psi.vivihudson (Instagram)",
    url: "https://www.instagram.com/psi.vivihudson/?hl=es"
  },
  {
    name: "Lic. Valeria Linero",
    specialty: "Psicólogo",
    provinces: ["Mendoza"],
    city: "Luján de Cuyo",
    address: "Rivadavia 88, Luján de Cuyo",
    phone: "Consultar",
    email: "vflinero@hotmail.com",
    hospital: "Consulta privada",
    experience: "Psicologa cognitiva conductual",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "private"
  },
  {
    name: "Espacio para Armar",
    specialty: "Centro Especializado",
    provinces: ["Buenos Aires"],
    city: "Lobos",
    address: "Laprida 178, Lobos bs.as y Alberdi 870, Lobos Bs As.",
    phone: "+54 2227 61-9748",
    whatsapp: "+54 9 11 6647-9010",
    email: "espacioparaarmarlobos@gmail.com",
    hospital: "Espacio para Armar",
    experience: "Equipo interdisciplinario de atención a niños y adolescentes con desafíos en el desarrollo / Atención a niños y adolescentes con TDAH desde una mirada cognitiva conductual",
    insurance: ["Consultar"],
    hours: "Consultar",
    type: "specialized_center",
    social: "@espacioparaarmarlobos (Instagram)",
    url: "https://instagram.com/espacioparaarmarlobos?igshid=1hpjjfbmytdt"
  },
  {
    name: "Lic. Paloma Legal",
    specialty: "Psicólogo",
    provinces: ["Buenos Aires"],
    city: "Bahía Blanca",
    address: "Por ahora solo atiende Online",
    phone: "+54 291 447-3955",
    email: "Autiasesoria@gmail.com",
    hospital: "Consulta privada online",
    experience: "Lic. en psicología (MP:2377) Terapia contextual, ACT. Trabaja con TDAH/TEA y neurodivergencias. Diplomada en TDAH por FLEDNI",
    insurance: ["Consulta privada; consultar reintegro"],
    hours: "Consultar",
    type: "private",
    social: "@autiasesoria (Instagram)",
    linkedin: "https://www.linkedin.com/in/autiasesoria-pl/"
  },

];

export default specialists;
