[test]
# `bun test` fails if line or function coverage drops below 100%
preload = ["./test/dom.ts", "./test/setup.ts"]
coverage = true
coveragePathIgnorePatterns = ["test/**"]
coverageThreshold = { lines = 1.0, functions = 1.0 }
