interface Especialista {
  nombre: string;
  especialidad: string;
  provincia: string;
  ciudad: string;
  direccion: string;
  telefono: string;
  email: string;
  hospital: string;
  experiencia: string;
  obraSocial: string[];
  horarios: string;
  tipo: string;
  url?: string;
  redes?: string;
  whatsapp?: string;
  linkedin?: string;
  emailFundacion?: string;
  turnos?: string;
}

const especialistas: Especialista[] = [
  // CAPITAL FEDERAL / GBA - ESPECIALISTAS ORIGINALES
  {
    nombre: "Dr. Osvaldo Rovere",
    especialidad: "Psiquiatra",
    provincia: "CABA",
    ciudad: "Recoleta",
    direccion: "Consulta privada",
    telefono: "+54 9 11 5483-7442",
    email: "osvaldorovere@gmail.com",
    hospital: "Consulta privada",
    experiencia: "Especialista en TDAH adultos",
    obraSocial: ["OSDE"],
    horarios: "Consultar",
    tipo: "privado",
  },
  {
    nombre: "Dra. Norma Cristina Echavarria",
    especialidad: "Psiquiatra",
    provincia: "Buenos Aires",
    ciudad: "Hurlingham",
    direccion: "Sargento Salazar 1536 entre Hidalgo y Richieri",
    telefono: "+54 11 4452-8765 | +54 9 11 6627-3265",
    whatsapp: "1541733220",
    email: "info@athentun.org",
    hospital: "ATHENTUN",
    experiencia: "Especialista en TDAH",
    obraSocial: ["Consultar"],
    horarios: "Mar-Vie 8:00-11:00",
    tipo: "centro_especializado",
    redes: "@espaciotdah (Instagram), /Athentun (Facebook)",
    url: "https://www.nechavarria.com/",
  },
  {
    nombre: "Dra. Paula Harris Racedo",
    especialidad: "Neuropsicóloga",
    provincia: "Buenos Aires",
    ciudad: "Beccar",
    direccion: "Consultar ubicación",
    telefono: "Consultar",
    whatsapp: "15 4437 2878",
    email: "paulaharrisracedo@gmail.com",
    hospital: "Consulta privada virtual",
    experiencia: "Especialista en TDAH",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    redes: "@phd_internacional (Instagram)",
    url: "https://sites.google.com/view/paulaharrisracedo/",
    linkedin: "https://www.linkedin.com/in/paula-harris-23a35a28/",
  },
  {
    nombre: "Lic. Marina Drake",
    especialidad: "Neuropsicóloga",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Esmeralda 961 6° Piso, Depto. H",
    telefono: "+54 11 4311-7864",
    email: "contacto@neuropsicologia.com.ar",
    hospital: "NEUROPSIC Consultorios",
    experiencia: "Neuropsicología",
    obraSocial: ["Consultar"],
    horarios: "Lun-Vie 14:00-19:00",
    tipo: "consultorio",
    url: "https://www.neuropsicologia.com.ar/",
    whatsapp: "541166659139",
  },
  {
    nombre: "Dra. Natalia Fiorentino",
    especialidad: "Neuropsicóloga",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "M.T de Alvear 1632",
    telefono: "0810-266-4203",
    email: "info@ineco.org.ar",
    hospital: "INECO - Instituto de Neurología Cognitiva",
    experiencia: "Programa de diagnóstico acelerado TDAH",
    obraSocial: ["Consultar"],
    horarios: "Lun-Vie",
    tipo: "instituto",
    url: "https://www.ineco.org.ar/programa-de-diagnostico-tdah/",
  },
  {
    nombre: "INECO - Instituto de Neurología Cognitiva",
    especialidad: "Centro",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "M.T de Alvear 1632",
    telefono: "0810-266-4203",
    email: "info@ineco.org.ar",
    hospital: "INECO",
    experiencia: "Instituto especializado en neurología cognitiva con programa específico de diagnóstico acelerado TDAH",
    obraSocial: ["Múltiples obras sociales"],
    horarios: "Lun-Vie 8:00-18:00",
    tipo: "centro_especializado",
    url: "https://www.ineco.org.ar/programa-de-diagnostico-tdah/",
  },
  {
    nombre: "Dra. Rosario Figueras",
    especialidad: "Psiquiatra",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "M.T de Alvear 1632",
    telefono: "+54 9 291 573-2919",
    email: "info@ineco.org.ar",
    hospital: "INECO - Instituto de Neurología Cognitiva",
    experiencia: "Especialista en TDAH",
    obraSocial: ["Consultar"],
    horarios: "Lun-Vie",
    tipo: "instituto",
  },
  {
    nombre: "Dra. Mirta Romalde",
    especialidad: "Psiquiatra",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "M.T de Alvear 1632",
    telefono: "+54 9 11 5929-9467",
    email: "info@ineco.org.ar",
    hospital: "INECO - Instituto de Neurología Cognitiva",
    experiencia: "Especialista en TDAH",
    obraSocial: ["Consultar"],
    horarios: "Lun-Vie",
    tipo: "instituto",
  },
  {
    nombre: "Dr. Gabriel Emilio Brenner",
    especialidad: "Psiquiatra",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Consultar ubicación",
    telefono: "+54 9 11 2794-0095",
    email: "info@inecap.org",
    hospital: "INECAP - Instituto de Neurociencia Cognitiva Aplicada",
    experiencia: "Especialista en TDAH",
    obraSocial: ["Consultar"],
    horarios: "Lun-Vie 9:00-20:00",
    tipo: "instituto",
    redes: "@inecap.tdah (Instagram), /inecap.org (Facebook)",
    url: "https://inecap.org/",
  },
  {
    nombre: "FLENI - Fundación para la Lucha contra las Enfermedades Neurológicas",
    especialidad: "Centro",
    provincia: "CABA",
    ciudad: "Belgrano",
    direccion: "Montañeses 2325, Belgrano, CABA",
    telefono: "+54 11 5777-3200",
    email: "info@fleni.org.ar",
    hospital: "FLENI",
    experiencia: "Fundación especializada en neurología con departamento de neurología cognitiva y neuropsiquiatría",
    obraSocial: ["Múltiples obras sociales"],
    horarios: "Lun-Vie 8:00-20:00",
    tipo: "centro_especializado",
    url: "https://www.fleni.org.ar/",
  },
  {
    nombre: "ATHENTUN - Centro de Atención y Tratamiento de TDAH",
    especialidad: "Centro",
    provincia: "Buenos Aires",
    ciudad: "Hurlingham",
    direccion: "Sargento Salazar 1536 entre Hidalgo y Richieri",
    telefono: "+54 11 4452-8765 | +54 9 11 6627-3265",
    email: "info@athentun.org",
    hospital: "ATHENTUN",
    experiencia: "Centro especializado exclusivamente en TDAH - Atención integral interdisciplinaria",
    obraSocial: ["Consultar"],
    horarios: "Mar-Vie 8:00-11:00",
    tipo: "centro_especializado",
    redes: "@espaciotdah (Instagram), /Athentun (Facebook)",
    url: "https://www.nechavarria.com/",
  },
  {
    nombre: "INECAP - Instituto de Neurociencia Cognitiva Aplicada",
    especialidad: "Centro",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Servicios 100% online",
    telefono: "Consultar",
    email: "info@inecap.org",
    hospital: "INECAP",
    experiencia: "Instituto especializado en diagnóstico y tratamiento de TDAH en jóvenes y adultos. Servicios basados en neurociencia cognitiva y medicina basada en evidencia",
    obraSocial: ["Consultar"],
    horarios: "Servicios online disponibles",
    tipo: "centro_especializado",
    redes: "@inecap.tdah (Instagram), /inecap.org (Facebook)",
    url: "https://inecap.org/",
  },
  {
    nombre: "Dra. Ariadna Echavarria",
    especialidad: "Psiquiatra",
    provincia: "Buenos Aires",
    ciudad: "Hurlingham",
    direccion: "Sargento Salazar 1536 entre Hidalgo y Richieri",
    telefono: "Consultar",
    whatsapp: "+54 9 11 2391-3130",
    email: "ariadnaechavarria@gmail.com",
    hospital: "ATHENTUN",
    experiencia: "Especialista en TDAH",
    obraSocial: ["Consultar"],
    horarios: "Mar-Vie 8:00-11:00",
    tipo: "centro_especializado",
  },
  {
    nombre: "Dr. Chrem Mendez Patricio",
    especialidad: "Neurólogo",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "FLENI",
    telefono: "+54 11 5777-3200",
    email: "Consultar",
    hospital: "FLENI - Neurología Cognitiva",
    experiencia: "Neurología Cognitiva - TDAH",
    obraSocial: ["Múltiples obras sociales"],
    horarios: "Lun-Vie 8:00-20:00",
    tipo: "hospital",
  },
  {
    nombre: "Dr. Juan Pablo García Lombardi",
    especialidad: "Neurólogo",
    provincia: "CABA",
    ciudad: "Belgrano",
    direccion: "FLENI - Montañeses 2325, 8vo piso, Belgrano, CABA",
    telefono: "+54 11 5777-3200",
    email: "jpabloglombardi@gmail.com",
    hospital: "FLENI",
    experiencia: "Neurología cognitiva/Neuropsiquiatria. Psiquiatra - Magíster en Neuropsicofarmacología. También atiende en La Plata - Instituto de Neurociencias Alexander Luria (02214511811)",
    obraSocial: ["Múltiples obras sociales"],
    horarios: "Lun-Vie 8:00-20:00",
    tipo: "hospital",
  },
  {
    nombre: "Dra. María Cecilia Rodríguez",
    especialidad: "Psiquiatra",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Hospital Italiano",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Hospital Italiano",
    experiencia: "Psiquiatría - Buen trato con pacientes",
    obraSocial: ["Múltiples obras sociales"],
    horarios: "Consultar",
    tipo: "hospital",
    url: "https://www1.hospitalitaliano.org.ar/#!/home/psiquiatria/inicio",
  },
  {
    nombre: "Dra. Cecilia Di Virgilio",
    especialidad: "Pediatra",
    provincia: "Buenos Aires",
    ciudad: "La Plata",
    direccion: "20 Nº 389 e/39 y 40",
    telefono: "+54 221 523-6577",
    email: "neurocienciascienn@gmail.com",
    hospital: "CIENN - Solo niños",
    experiencia: "Centro especializado en neurodesarrollo infantil",
    obraSocial: ["Consultar"],
    horarios: "Lun-Vie 8:00-20:00, Sáb 9:00-13:00",
    tipo: "centro_especializado",
    whatsapp: "(221) 552-6999",
    turnos: "423-3792",
    redes: "@c.i.e.n.n (Instagram), /neurocienciasCIENN (Facebook)",
  },
  {
    nombre: "Dra. Silvina Gutierrez",
    especialidad: "Psiquiatra",
    provincia: "Buenos Aires",
    ciudad: "La Plata",
    direccion: "115 Nro. 425 (Clínica San Juan)",
    telefono: "+54 221 641-9144",
    email: "Consultar",
    hospital: "Clínica San Juan",
    experiencia: "Especialista en TDAH",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "clinica",
  },
  {
    nombre: "Lic. Luis Santiago Vaggione",
    especialidad: "Psicólogo",
    provincia: "Córdoba",
    ciudad: "Córdoba Capital",
    direccion: "Fundación Nascendi",
    telefono: "Consultar",
    email: "lsvaggione@yahoo.com.ar",
    hospital: "Fundación Nascendi",
    emailFundacion: "fundacionnascendi@gmail.com",
    experiencia: "Especialista en TDAH",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "fundacion",
    redes:
      "@luissantiagovaggione (Instagram), /luissantiago.vaggione (Facebook)",
  },

  // PSICOPEDAGOGÍA
  {
    nombre: "Crianza Positiva",
    especialidad: "Psicopedagogía",
    provincia: "CABA",
    ciudad: "Caballito",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Centro Categorizado y Equipo Interdisciplinario",
    experiencia: "Problematicas de Conducta y Dificultades Emocionales",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    url: "https://www.google.com/search?q=Crianza+Positiva+Buenos+Aires&stick=H4sIAAAAAAAAAONgecT4npFb4OWPe8JSTxknrTl5jfEeIxdXcEZ-uWteSWZJpVAAFxuUpcIlKMWrn65vaJhlYGRakZxrqcEgxc-FKiSloMTFe3x59GtR41Uad7WEOEUfWBRxn94zVVByJd-LuqXiM4Q0uTiDUnMSS1JTQvKFZLh4pTj1c_UNDHMqTXOBBnJzIbhKwUbuuy5NO8fmKMgABEdSwx2kNJWEuThCEivy8_JzKwUP_P-_____9_ZKQlzsnsU--cmJOYKv9jEm6HwEinFyAjUd2Lz8vb0WQ9O-FYfYWDgYBRh4FrHKOhdlJuZVJSoE5BdnlmSWJSo4labm5RcrOGYWpRYDAJy1e1EVAQAA&sa=X&ved=2ahUKEwjp74CJq7HqAhUSGKwKHePXBvYQ6RMwC3oECAwQBA&biw=1440&bih=789"
  },
  {
    nombre: "Lic. Liliana Fonseca",
    especialidad: "Psicopedagogía",
    provincia: "Buenos Aires",
    ciudad: "San Isidro",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psicopedagoga",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    url: "http://aprendizajeyfamilia.com/"
  },
  {
    nombre: "Lic. Margarita Peña",
    especialidad: "Psicopedagogía",
    provincia: "Buenos Aires",
    ciudad: "Bella Vista",
    direccion: "San Martín 2325, Bella Vista, Bs. As.",
    telefono: "Consultar",
    whatsapp: "11 3005 4000",
    email: "maggiepenia@gmail.com",
    hospital: "Consulta privada",
    experiencia: "Psicopedagogía",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Centro de integración escolar",
    especialidad: "Centro",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Consultar ubicación específica",
    telefono: "+54 11 4326-1971",
    whatsapp: "1550637542",
    email: "contacto@cieintegracion.com",
    hospital: "Centro de integración escolar",
    experiencia: "Acompañamiento escolar",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    url: "http://www.integracionescolar.com.ar/contacto/"
  },
  {
    nombre: "Lic. Graciela Bernardi",
    especialidad: "Psicopedagogía",
    provincia: "Buenos Aires",
    ciudad: "Zona Oeste",
    direccion: "Consultar ubicación específica",
    telefono: "+54 9 11 5932-7259",
    email: "gracielabernardi@yahoo.com",
    hospital: "Consulta privada",
    experiencia: "Psicopedagoga, especialista en neurodesarrollo",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Escuela de Equitación Hipocampo",
    especialidad: "Centro",
    provincia: "CABA",
    ciudad: "Palermo",
    direccion: "Av. Figueroa Alcorta 5100, Palermo, CABA",
    telefono: "+54 9 11 5015-2666",
    email: "Consultar",
    hospital: "Escuela de Equitación Hipocampo",
    experiencia: "Equinoterapia complementaria para TDAH - mejora organización, atención, funciones ejecutivas y autoestima",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    url: "http://www.escuelahipocampo.org/equinoterapia.html"
  },
  {
    nombre: "Lic. Antonela Rubio",
    especialidad: "Psicopedagogía",
    provincia: "Buenos Aires",
    ciudad: "La Plata",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "antonela.rubio@hotmail.com",
    hospital: "Consulta privada",
    experiencia: "Formada en TDAH y aprendizaje en niños y adolescentes",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Analía Dussin",
    especialidad: "Psicopedagogía",
    provincia: "Córdoba",
    ciudad: "San Francisco",
    direccion: "Paraguay 1565, San Francisco, Córdoba",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Lic. en Psicopedagogía",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    redes: "@analiadussin.psp (Instagram)",
    url: "https://instagram.com/analiadussin.psp?igshid=19bgkdtzndn9e"
  },
  {
    nombre: "Lic. Romina del Río",
    especialidad: "Psicopedagogía",
    provincia: "Buenos Aires",
    ciudad: "San Isidro",
    direccion: "Brasil 724, San Isidro",
    telefono: "Consultar",
    whatsapp: "+54 9 11 6140-9612",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psicopedagoga",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. María Guillermina Mujica",
    especialidad: "Psicopedagogía",
    provincia: "Buenos Aires",
    ciudad: "Bernal",
    direccion: "Calle Ituzaingo 456 Bernal",
    telefono: "+54 11 4251-6988",
    email: "Guillerminamujica@yahoo.com.ar",
    hospital: "Consulta privada",
    experiencia: "Psicopedagoga - También atiende online",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Ines Christie Newbery",
    especialidad: "Psicopedagogía",
    provincia: "CABA/Buenos Aires",
    ciudad: "Recoleta/Bella Vista",
    direccion: "Callao 1673, Recoleta, CABA | Scott 2488, Bella Vista, Buenos Aires",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psicopedagoga Clínica - Atiende en dos consultorios",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "ÁBACO Interdisciplina",
    especialidad: "Centro",
    provincia: "Córdoba",
    ciudad: "Río Tercero",
    direccion: "Esperanza 1270 1278, X5850 Río Tercero, Córdoba",
    telefono: "+54 3571 41-1469",
    email: "Consultar",
    hospital: "Centro interdisciplinario",
    experiencia: "Centro interdisciplinario",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado"
  },
  {
    nombre: "Lic. Antonella Rizzo",
    especialidad: "Psicopedagogía",
    provincia: "CABA",
    ciudad: "Caballito",
    direccion: "Av. Rivadavia y Acoyte (a 1 cuadra) zona Caballito",
    telefono: "+54 9 11 4916-3164",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Licencia en psicopedagogía neurocognitiva",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Florencia Foglia",
    especialidad: "Psicopedagogía",
    provincia: "Santa Fe",
    ciudad: "Santa Fe",
    direccion: "Gdor. Crespo 2938, S3000 Santa Fe de la Vera Cruz",
    telefono: "+54 9 358 429-8457",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psicopedagoga",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },

  // PSIQUIATRAS Y NEURÓLOGOS ADICIONALES
  {
    nombre: "Dra. Santillan",
    especialidad: "Pediatra",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Instituto Niba",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Instituto Niba",
    experiencia: "Pediatra y neuróloga",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "instituto",
    url: "https://www.niba.com.ar/"
  },
  {
    nombre: "Equipo de neurología - Hospital italiano",
    especialidad: "Centro",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Hospital Italiano",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Hospital Italiano",
    experiencia: "Equipo de neurología",
    obraSocial: ["Hospital Italiano"],
    horarios: "Consultar",
    tipo: "hospital",
    url: "https://www.hospitalitaliano.org.ar/#!/home/neurologia/seccion/14251"
  },
  {
    nombre: "Dra. Paola Grabow",
    especialidad: "Psiquiatra",
    provincia: "CABA",
    ciudad: "Belgrano",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psiquiatría infantil",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    linkedin: "https://ar.linkedin.com/in/paola-grabow-1b8b5941?src=aff-lilpar&veh=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&trk=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&clickid=2pe2qITY8xyOT42wUx0Mo3chUkiUlV3TUQUFVM0&irgwc=1"
  },
  {
    nombre: "Dr. Claudio Michanie",
    especialidad: "Psiquiatra",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psiquiatría Infantil y Adolescente",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    url: "https://psiquiatria.com/directorio/claudio-michanie"
  },
  {
    nombre: "Dr. Guillermo Bernaldo de Quiros",
    especialidad: "Neurólogo",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Neurologo infantil",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    url: "https://www.google.com/search?ei=RkH_Xs-VEcu1tAaw86XYCA&q=Dr+Guillermo+Bernaldo+de+Quiros+bs+as+&oq=Dr+Guillermo+Bernaldo+de+Quiros+bs+as+&gs_lcp=CgZwc3ktYWIQAzIFCCEQoAE6AggAUO5YWK2KAWD1iwFoBXAAeACAAboBiAHUDJIBBDAuMTOYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwjP0IqOprHqAhXLGs0KHbB5CYsQ4dUDCAw&uact=5"
  },
  {
    nombre: "Dr. Pablo Jorrat",
    especialidad: "Neurólogo",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Neurólogo infantil",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    url: "https://www.google.com/search?q=dr+Pablo+Jorrat+bs+as&oq=dr+Pablo+Jorrat+bs+as&aqs=chrome..69i57j0l7.2214j0j9&sourceid=chrome&ie=UTF-8"
  },
  {
    nombre: "Dr. Juan Tripoli",
    especialidad: "Neurólogo",
    provincia: "CABA",
    ciudad: "Belgrano",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Neurología Pediátrica",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    url: "http://pediatriabelgranor.com/nosotros/dr-juan-tripoli/"
  },
  {
    nombre: "Dra. Norma Taddey",
    especialidad: "Psiquiatra",
    provincia: "Buenos Aires",
    ciudad: "Vicente López",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psiquiatra infanto juvenil",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    linkedin: "https://ar.linkedin.com/in/norma-taddey-10975422?src=aff-lilpar&veh=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&trk=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&clickid=2pe2qITY8xyOT42wUx0Mo3chUkiUlDU6UQUFVM0&irgwc=1"
  },
  {
    nombre: "Dra. Sara Panossian",
    especialidad: "Neurólogo",
    provincia: "Buenos Aires",
    ciudad: "Bella Vista",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Neuróloga infanto juvenil",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    url: "https://www.doxadoctor.com/medicos/Panossian-Sara-Irene"
  },
  {
    nombre: "Dr. Diego Miniño",
    especialidad: "Psiquiatra",
    provincia: "Buenos Aires",
    ciudad: "Lanús",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    whatsapp: "+54 9 11 4424-8825",
    email: "diegoadrianminino@gmail.com",
    hospital: "Consulta privada",
    experiencia: "Psiquiatra",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    url: "https://www.saludmentallanus.com/staff"
  },
  {
    nombre: "CIENN",
    especialidad: "Centro",
    provincia: "Buenos Aires",
    ciudad: "La Plata",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Centro Modelo de Neurociencias Infantojuvenil",
    experiencia: "Diagnosticos y Tratamientos Interdisciplinarios. Neurodesarrollo y Nutrición",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    url: "http://cienn.com.ar/"
  },
  {
    nombre: "Dr. Mariano Pala",
    especialidad: "Pediatra",
    provincia: "Buenos Aires",
    ciudad: "Mar del Plata",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Pediatra y psiquiatra infanto juvenil",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    linkedin: "https://ar.linkedin.com/in/mariano-pala-6294768a"
  },
  {
    nombre: "Dr. Marcon Laureano",
    especialidad: "Neurólogo",
    provincia: "Buenos Aires",
    ciudad: "Mar del Plata",
    direccion: "INEDEM",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Instituto de Neurología y Desarrollo Marcón",
    experiencia: "Instituto de Neurología y Desarrollo",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "instituto",
    url: "http://inedem.com.ar/"
  },
  {
    nombre: "Dr. Nicolás Schnitzler",
    especialidad: "Neurólogo",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Fundación Favaloro",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Fundación Favaloro",
    experiencia: "Jefe de Neurología Infantil",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "hospital",
    url: "https://www.fundacionfavaloro.org/neurologia-infantil/"
  },
  {
    nombre: "Dra. María Susana Mosquera",
    especialidad: "Psiquiatra",
    provincia: "Buenos Aires",
    ciudad: "San Isidro",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psiquiatra",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    url: "https://www.doctoraliar.com/maria-susana-mosquera/psiquiatra/san-isidro"
  },
  {
    nombre: "Dra. Varinia A. Frau Alveal",
    especialidad: "Psiquiatra y Legista",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Médico Psiquiatra y Legista. Docente",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    url: "https://www.google.com/search?ei=Eln_XqLbI4KQtQWj6ZyACA&q=Varinia+Frau+Alveal+psiquiatria+&oq=Varinia+Frau+Alveal+psiquiatria+&gs_lcp=CgZwc3ktYWIQAzIFCCEQoAEyBQghEKABOgIIADoGCAAQFhAeUITNAVja3gFg3t8BaABwAHgAgAGwBYgBkhKSAQczLTIuMi4xmAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwiirI_nvLHqAhUCSK0KHaM0B4AQ4dUDCAw&uact=5"
  },
  {
    nombre: "Dr. Adi Javier Nadin",
    especialidad: "Neurólogo",
    provincia: "Mendoza",
    ciudad: "Godoy Cruz",
    direccion: "Panamericana 2650, Godoy Cruz, Mendoza",
    telefono: "+54 261 439-8010",
    email: "Consultar",
    hospital: "Centro Médico Palmares",
    experiencia: "Neurología en niños y adolescentes",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    url: "http://www.centromedicopalmares.com/medicos/dr-adi-javier-nadin/"
  },
  {
    nombre: "Dra. Carolina Remedi",
    especialidad: "Psiquiatra",
    provincia: "Córdoba",
    ciudad: "Córdoba Capital",
    direccion: "Av. Velez Sarsfield 1460",
    telefono: "Consultar",
    email: "carore.remedi101@gmail.com",
    hospital: "CETES",
    experiencia: "Psiquiatra",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    url: "http://cetes.com.ar/ya-nos-trasladamos/"
  },
  {
    nombre: "Dr. José Dominguez",
    especialidad: "Psiquiatra",
    provincia: "Santa Fe",
    ciudad: "Santa Fe",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psiquiatra",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    url: "https://www.google.com/search?q=Jos%C3%A9+Dom%C3%ADnguez+psiquiatra+santa+fe&oq=Jos%C3%A9+Dom%C3%ADnguez+psiquiatra+santa+fe&aqs=chrome..69i57.2901j0j4&sourceid=chrome&ie=UTF-8"
  },
  {
    nombre: "Dra. Mariela Labath",
    especialidad: "Neurólogo",
    provincia: "Santa Fe",
    ciudad: "Paraná",
    direccion: "Consultorios Interdisciplinarios Puerto Nuevo",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consultorios Interdisciplinarios Puerto Nuevo",
    experiencia: "Neurología",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "consultorio",
    redes: "/Consultorios-Interdisciplinarios-Puerto-Nuevo-902522106535440 (Facebook)",
    url: "https://es-la.facebook.com/pg/Consultorios-Interdisciplinarios-Puerto-Nuevo-902522106535440/about/"
  },
  {
    nombre: "Dr. Eduardo Monese",
    especialidad: "Pediatra",
    provincia: "Santa Fe",
    ciudad: "Santa Fe Capital",
    direccion: "Mendoza 3373, Santa Fe Capital",
    telefono: "+54 342 453-0374",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Neurólogo y pediatra",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    url: "https://www.doctoraliar.com/eduardo-j-monese/pediatra/santa-fe-capital"
  },
  {
    nombre: "Dra. Viviana Rios",
    especialidad: "Neurólogo",
    provincia: "Santa Fe",
    ciudad: "Santa Fe",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Neuróloga",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    url: "https://www.google.com/search?q=Dra+Viviana+Rios+santa+fe&oq=Dra+Viviana+Rios+santa+fe+&aqs=chrome..69i57.1746j0j4&sourceid=chrome&ie=UTF-8"
  },
  {
    nombre: "Dra. Stephanie Schon",
    especialidad: "Psiquiatra",
    provincia: "Buenos Aires",
    ciudad: "Mar del Plata",
    direccion: "Consultar ubicación específica",
    telefono: "+54 223 451-9651",
    email: "stephyschon@hotmail.com",
    hospital: "Consulta privada",
    experiencia: "Psiquiatra",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Dr. Ricardo Rojas",
    especialidad: "Psiquiatra",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    whatsapp: "+54 9 223 579 6683",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psiquiatra adultos, adicciones y TDAH",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Dra. Natalia Barrios",
    especialidad: "Psiquiatra",
    provincia: "Buenos Aires",
    ciudad: "La Matanza",
    direccion: "Consultar ubicación específica",
    telefono: "+54 9 11 4157-9425",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psiquiatra",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "CPG Salud",
    especialidad: "Centro",
    provincia: "Buenos Aires",
    ciudad: "Zona Norte",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    whatsapp: "+54 9 11 3039-0164",
    email: "Consultar",
    hospital: "CPG Salud",
    experiencia: "Institución privada especializada en Salud Mental - asistencia, diagnóstico y tratamiento desde 2005",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    url: "http://www.cpgsalud.com.ar/contacto.html"
  },
  {
    nombre: "Dra. Stella Maris Ramirez",
    especialidad: "Psiquiatra",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Hospital Churruca Visca",
    telefono: "+54 11 4909-4100 (interno 4847)",
    email: "Consultar",
    hospital: "Hospital Churruca Visca - Servicio de Salud Mental Infanto Juvenil",
    experiencia: "Psiquiatra del Servicio de Salud Mental Infanto Juvenil",
    obraSocial: ["Hospital público"],
    horarios: "Consultar",
    tipo: "hospital"
  },
  {
    nombre: "Integral-mente",
    especialidad: "Centro",
    provincia: "Buenos Aires",
    ciudad: "Villa Luzuriaga",
    direccion: "Miró 2534, Villa Luzuriaga, Bs. As.",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Integral-mente",
    experiencia: "Equipo Interdisciplinario de Desarrollo",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    whatsapp: "+ 54 9 11 6605-4391",
    url: "http://www.integral-mente.com.ar/"
  },
  {
    nombre: "Dr. Galli",
    especialidad: "Neurólogo",
    provincia: "Santa Fe",
    ciudad: "Rafaela",
    direccion: "Calle 25 de Mayo 2048 - AMUR",
    telefono: "+54 342 452-5891",
    whatsapp: "(0342) 4535606",
    email: "Consultar",
    hospital: "AMUR",
    experiencia: "Neurólogo y Neuropsicologo - Solo evaluación. No tiene equipo de profesionales (Psiquiatra y Psicólogo) para el tratamiento",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado"
  },
  {
    nombre: "Dra. Riera",
    especialidad: "Psiquiatra",
    provincia: "Mendoza",
    ciudad: "Mendoza",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    whatsapp: "+54 9 261 472-4886",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psiquiatra Infantojuvenil",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Dr. Guido Norberto Luppi",
    especialidad: "Pediatra",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Uruguay 1134 2do piso, Capital Federal",
    telefono: "+54 11 5217-1382",
    email: "drguidoluppi@gmail.com",
    hospital: "Consulta privada",
    experiencia: "Medico pediatra y psiquiatra innfantojuvenil. Realiza diagnóstico y tratamiento de TDAH y hace consultas virtuales y presenciales",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    whatsapp: "11 4412 0880",
    url: "https://forms.gle/xym8jNQ6xMsSBT5T8"
  },

  // PEDIATRAS
  {
    nombre: "Dra. Ángeles Menendez",
    especialidad: "Pediatra del Neurodesarrollo",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Centro Pediátrico del Desarrollo Creciendo Juntos",
    telefono: "+54 9 11 5704-4655",
    email: "Consultar",
    hospital: "Centro Pediátrico del Desarrollo Creciendo Juntos",
    experiencia: "Pediatra del neurodesarrollo",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    redes: "/CentroPediatricoCreciendoJuntos (Facebook)",
    url: "https://es-la.facebook.com/pg/CentroPediatricoCreciendoJuntos/about/?ref=page_internal"
  },
  {
    nombre: "Dra. Debora Abolsky",
    especialidad: "Pediatra",
    provincia: "Buenos Aires",
    ciudad: "Luján",
    direccion: "Consultar ubicación específica",
    telefono: "+54 232 047-0009",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Pediatra",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Dr. Juan José López Luro",
    especialidad: "Pediatra del Desarrollo",
    provincia: "Río Negro",
    ciudad: "Neuquén",
    direccion: "Consultar ubicación específica",
    telefono: "+54 299 467-5599",
    email: "consultoriolopezlurovitale@gmail.com",
    hospital: "Consulta privada",
    experiencia: "Pediatra del Desarrollo",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },

  // PSICÓLOGOS Y TCC
  {
    nombre: "Lic. Facundo Torres",
    especialidad: "Psicólogo",
    provincia: "Buenos Aires",
    ciudad: "Tigre",
    direccion: "CEPSIN",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "CEPSIN",
    experiencia: "Psicólogo infantojuvenil",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    url: "https://www.cepsin.com.ar/psicologos.html"
  },
  {
    nombre: "Lic. Cecilia Cid",
    especialidad: "Psicólogo",
    provincia: "Buenos Aires",
    ciudad: "Zona Oeste",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    whatsapp: "+54 9 11 6116-9753",
    email: "ceciliascid@gmail.com",
    hospital: "Consulta privada",
    experiencia: "Psicóloga niños y adolescentes TCC",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Lorena Lancha",
    especialidad: "Psicólogo",
    provincia: "Buenos Aires",
    ciudad: "Zona Oeste",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    whatsapp: "11 6605-4391",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psicóloga especializada en neurodesarrollo. TCC",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Bettina Arredondo",
    especialidad: "Psicólogo",
    provincia: "Buenos Aires",
    ciudad: "Temperley",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    whatsapp: "+54 9 11 5772-5296",
    email: "psiarredondobettina@gmail.com",
    hospital: "Consulta privada",
    experiencia: "Psicologa cognitiva",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Laura Alcocer",
    especialidad: "Psicólogo",
    provincia: "Buenos Aires",
    ciudad: "La Plata",
    direccion: "CETECO",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "CETECO",
    experiencia: "Psicóloga, directora de CETECO",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    url: "http://www.cetecolaplata.com.ar/"
  },
  {
    nombre: "Lic. Sharon Suzanne",
    especialidad: "Psicólogo",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    whatsapp: "+54 11 2253 1362",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psicologa infanto-juvenil - autismo, TDAH, TEA, dislexia. Enfoque psicoeducativo",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    linkedin: "https://ar.linkedin.com/in/sharon-suzanne-mujica-33546338?src=aff-lilpar&veh=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&trk=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&clickid=2pe2qITY8xyOT42wUx0Mo3chUkiUlIQKUQUFVM0&irgwc=1"
  },
  {
    nombre: "Lic. Alberto Luis Fernandez",
    especialidad: "Psicólogo",
    provincia: "Córdoba",
    ciudad: "Córdoba Capital",
    direccion: "Centro Cortex: Calle Chile 279",
    telefono: "+54 351 662-5405",
    email: "Consultar",
    hospital: "Centro Cortex",
    experiencia: "Psicólogo",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    url: "https://www.cortexneuroterapias.com.ar/quienes-somos"
  },
  {
    nombre: "Lic. Luciana Tapia",
    especialidad: "Psicólogo",
    provincia: "Buenos Aires",
    ciudad: "Necochea",
    direccion: "Consultar ubicación específica",
    telefono: "+54 226 248-0577",
    email: "tapialuciana@hotmail.com",
    hospital: "Consulta privada",
    experiencia: "Psicóloga cognitivo conductual",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Iris Wolff",
    especialidad: "Psicólogo",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    email: "irisworff01@gmail.com",
    hospital: "Consulta privada",
    experiencia: "Psicóloga cognitiva",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Elisa Chisleanschi",
    especialidad: "Psicólogo",
    provincia: "Buenos Aires",
    ciudad: "Bella Vista",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    whatsapp: "11 4666-4395",
    email: "tinachisle@hotmail.com",
    hospital: "Consulta privada",
    experiencia: "Psicóloga",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Eleonora Giusti",
    especialidad: "Psicólogo",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Consultar ubicación específica",
    telefono: "+54 9 11 6229-7355",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psicologa adultos cognitiva",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "TCM Terapia Cognitiva",
    especialidad: "Centro",
    provincia: "Buenos Aires",
    ciudad: "La Matanza",
    direccion: "Zaqueira 6880, Bs. As.",
    telefono: "+54 9 11 3066-6880",
    email: "Consultar",
    hospital: "TCM Terapia Cognitiva",
    experiencia: "Terapia cognitiva",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    redes: "@tcm.psic (Instagram)",
    url: "https://tcmcognitiva.com/"
  },
  {
    nombre: "Lic. Carolina Piñero",
    especialidad: "Psicólogo",
    provincia: "Buenos Aires",
    ciudad: "Tandil",
    direccion: "Consultar ubicación específica",
    telefono: "+54 9 11 4039-2057",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Piscóloga",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Alejandra Perez",
    especialidad: "Neuropsicóloga",
    provincia: "Buenos Aires",
    ciudad: "San Isidro",
    direccion: "Alem 265, San Isidro",
    telefono: "+54 9 11 6593-1494",
    email: "alejandraperezturnos@gmail.com",
    hospital: "Consulta privada",
    experiencia: "Psicóloga especializada en neuropsicología",
    obraSocial: ["Particular"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Silvana Soave",
    especialidad: "Psicólogo",
    provincia: "Buenos Aires",
    ciudad: "Necochea",
    direccion: "Calle 60-2780",
    telefono: "+54 226 253-0111",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psicóloga cognitivo conductual",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Manuel Pastene",
    especialidad: "Psicólogo",
    provincia: "Buenos Aires",
    ciudad: "Vicente Lopez",
    direccion: "Santa Rosa 1393, Vicente Lopez",
    telefono: "Consultar",
    whatsapp: "11 4089 7200",
    email: "manuelpastene@gmail.com",
    hospital: "Consulta privada",
    experiencia: "Lic. en Psicología y especializado en el diagnóstico y tratamiento para jóvenes y adultos con TDAH",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Romina Rosbelke",
    especialidad: "Psicólogo",
    provincia: "Buenos Aires",
    ciudad: "Quilmes",
    direccion: "Calle brandzen 253, Quilmes",
    telefono: "+54 9 11 6714-2890",
    email: "Romina_rosbelke@hotmail.com",
    hospital: "Consulta privada",
    experiencia: "Psicóloga infantil - Atiende también online",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Maria Gabriela Marina",
    especialidad: "Psicólogo",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Atiende online",
    telefono: "+54 9 11 3230-6783",
    email: "mariamarinapsi@gmail.com",
    hospital: "Consulta privada online",
    experiencia: "Licenciada en psicología/Terapeuta cognitivo conductual /Terapeuta EMDR",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Patricia Simao",
    especialidad: "Psicólogo",
    provincia: "CABA",
    ciudad: "CABA",
    direccion: "Consultar ubicación específica",
    telefono: "Consultar",
    whatsapp: "+54 9 11 6494 5376",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psicologa infantil especializada en altas capacidades y TDAH",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Lila Perinot",
    especialidad: "Neuropsicóloga",
    provincia: "CABA",
    ciudad: "Palermo",
    direccion: "Ciudad de la Paz 561, Palermo",
    telefono: "+5491131478100",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Neuropsicologa - Adultos",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Celeste Campano",
    especialidad: "Psicólogo",
    provincia: "CABA",
    ciudad: "Caballito",
    direccion: "Calle Lautaro 46 (Esquina Avenida Rivadavia) Caballito",
    telefono: "Consultar",
    email: "Consultar",
    hospital: "Crianza positiva",
    experiencia: "Crianza positiva y trabaja en talleres de habilidades sociales con grupos de niños con TDAH",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    redes: "@crianzapositivaargentina (Instagram)",
    url: "https://instagram.com/crianzapositivaargentina?igshid=YmMyMTA2M2Y="
  },
  {
    nombre: "Lic. Anahi Lujan Garayo",
    especialidad: "Psicólogo",
    provincia: "La Pampa",
    ciudad: "Santa Rosa",
    direccion: "Av. Belgrano Norte, Santa Rosa 6300 La Pampa",
    telefono: "Consultar",
    whatsapp: "+54 9 2954 33-6970",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psicologa",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Castro Zamparella Tatiana",
    especialidad: "Psicólogo",
    provincia: "Córdoba",
    ciudad: "Córdoba Capital",
    direccion: "CNR",
    telefono: "Consultar",
    email: "cnrcerebroysalud@gmail.com",
    hospital: "CNR",
    experiencia: "Psicóloga",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado"
  },
  {
    nombre: "Lic. Maria Laura De Feo",
    especialidad: "Psicólogo",
    provincia: "Santa Fe",
    ciudad: "Santa Fe",
    direccion: "San Jerónimo 2020, Santa Fe de la Vera Cruz",
    telefono: "+5493425032995",
    email: "Consultar",
    hospital: "Consulta privada",
    experiencia: "Psicóloga (TCC)",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Lic. Vivian Alexia Hudson Figueroa",
    especialidad: "Psicólogo",
    provincia: "CABA",
    ciudad: "Belgrano",
    direccion: "Belgrano (a una cuadra de Lacroze y cabildo)",
    telefono: "+54 9 11 5528-4448",
    email: "vivianalexia@hotmail.com",
    hospital: "Consulta privada",
    experiencia: "Psicóloga de adultos y parejas - Atiende online o presencial",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado",
    redes: "@psi.vivihudson (Instagram)",
    url: "https://www.instagram.com/psi.vivihudson/?hl=es"
  },
  {
    nombre: "Lic. Valeria Linero",
    especialidad: "Psicólogo",
    provincia: "Mendoza",
    ciudad: "Luján de Cuyo",
    direccion: "Rivadavia 88, Luján de Cuyo",
    telefono: "Consultar",
    email: "vflinero@hotmail.com",
    hospital: "Consulta privada",
    experiencia: "Psicologa cognitiva conductual",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "privado"
  },
  {
    nombre: "Espacio para Armar",
    especialidad: "Centro",
    provincia: "Buenos Aires",
    ciudad: "Lobos",
    direccion: "Laprida 178, Lobos bs.as y Alberdi 870, Lobos Bs As.",
    telefono: "+54 2227 61-9748",
    whatsapp: "11-66479010",
    email: "espacioparaarmarlobos@gmail.com",
    hospital: "Espacio para Armar",
    experiencia: "Equipo interdisciplinario de atención a niños y adolescentes con desafíos en el desarrollo / Atención a niños y adolescentes con TDAH desde una mirada cognitiva conductual",
    obraSocial: ["Consultar"],
    horarios: "Consultar",
    tipo: "centro_especializado",
    redes: "@espacioparaarmarlobos (Instagram)",
    url: "https://instagram.com/espacioparaarmarlobos?igshid=1hpjjfbmytdt"
  },
  {
    nombre: "Lic. Paloma Legal",
    especialidad: "Psicólogo",
    provincia: "Buenos Aires",
    ciudad: "Bahía Blanca",
    direccion: "Por ahora solo atiende Online",
    telefono: "+54 291 447-3955",
    email: "Autiasesoria@gmail.com",
    hospital: "Consulta privada online",
    experiencia: "Lic. en psicología (MP:2377) Terapia contextual, ACT. Trabaja con TDAH/TEA y neurodivergencias. Diplomada en TDAH por FLEDNI",
    obraSocial: ["Consulta privada, pero puede trabajar con obra sociales por reintegro"],
    horarios: "Consultar",
    tipo: "privado",
    redes: "@autiasesoria (Instagram)",
    linkedin: "https://www.linkedin.com/in/autiasesoria-pl/"
  },

];

export default especialistas;
